# Generated by Django 5.2.5 on 2025-08-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='number_phone1',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='acount',
            name='number_phone2',
            field=models.BigIntegerField(),
        ),
    ]
