# Generated by Django 5.2.5 on 2025-08-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_acount_number_phone1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='number_phone1',
            field=models.BigIntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='acount',
            name='number_phone2',
            field=models.BigIntegerField(max_length=11),
        ),
    ]
