# Generated by Django 5.2.5 on 2025-08-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userinvite_userpercent'),
    ]

    operations = [
        migrations.AddField(
            model_name='acount',
            name='percent',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
