# Generated by Django 5.2.5 on 2025-08-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='describe',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
