# Generated by Django 5.2.5 on 2025-08-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0002_product_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price1', models.PositiveBigIntegerField()),
                ('price2', models.PositiveBigIntegerField()),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.PositiveBigIntegerField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
