# Generated by Django 5.2.5 on 2025-08-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0003_discount_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='picture',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
