# Generated by Django 5.2.5 on 2025-08-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0004_discount_picture_alter_discount_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='price2',
            new_name='price',
        ),
    ]
