# Generated by Django 5.2.5 on 2025-08-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0005_rename_price2_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='describe',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='special',
            name='describe',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
