# Generated by Django 5.2.5 on 2025-08-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0006_discount_describe_special_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_name',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='discount',
            name='url_name',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='url_name',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='special',
            name='url_name',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='subset',
            name='url_name',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
