# Generated by Django 5.2.5 on 2025-08-22 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0007_category_url_name_discount_url_name_product_url_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sended', models.CharField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('receive_code', models.PositiveBigIntegerField(default=0)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghoghnoos.discount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghoghnoos.product')),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghoghnoos.special')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
