# Generated by Django 5.2.5 on 2025-08-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0010_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dark_brown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='light_brown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='pea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='wood',
            field=models.BooleanField(default=False),
        ),
    ]
