# Generated by Django 5.2.5 on 2025-08-23 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0011_product_dark_brown_product_light_brown_product_pea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dark_brown',
        ),
        migrations.RemoveField(
            model_name='product',
            name='light_brown',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pea',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wood',
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.PositiveBigIntegerField()),
                ('count', models.PositiveSmallIntegerField()),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ghoghnoos.discount')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ghoghnoos.product')),
                ('special', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ghoghnoos.special')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('colm', models.IntegerField()),
                ('price', models.PositiveBigIntegerField()),
                ('count', models.PositiveSmallIntegerField()),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ghoghnoos.discount')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ghoghnoos.product')),
                ('special', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ghoghnoos.special')),
            ],
        ),
    ]
