# Generated by Django 5.2.5 on 2025-08-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0012_remove_product_dark_brown_remove_product_light_brown_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colors',
            old_name='name',
            new_name='name_color',
        ),
        migrations.RenameField(
            model_name='colors',
            old_name='price',
            new_name='price_color',
        ),
    ]
