# Generated by Django 5.2.5 on 2025-08-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0014_alter_order_discount_alter_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colors',
            name='name_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='colors',
            name='price_color',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='colm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
