# Generated by Django 5.2.5 on 2025-08-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0015_alter_colors_count_alter_colors_name_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='price',
            new_name='price_size',
        ),
    ]
