# Generated by Django 5.2.5 on 2025-08-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0016_rename_price_size_price_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receive_code',
        ),
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sended',
            field=models.CharField(blank=True, null=True),
        ),
    ]
