# Generated by Django 5.2.5 on 2025-08-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0017_remove_order_receive_code_order_color_order_describe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='add_buy_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='buy_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='buy_history',
            field=models.BooleanField(default=False),
        ),
    ]
