# Generated by Django 5.2.5 on 2025-08-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0018_order_add_buy_page_order_buy_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_added',
            field=models.CharField(blank=True, null=True),
        ),
    ]
