# Generated by Django 5.2.5 on 2025-08-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0019_order_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count_action',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='count_history',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
