# Generated by Django 5.2.5 on 2025-08-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0020_order_count_action_order_count_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='count',
        ),
        migrations.AddField(
            model_name='discount',
            name='totall_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='color_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='size_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='totall_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='special',
            name='totall_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
