# Generated by Django 5.2.5 on 2025-08-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0024_discount_likes_product_likes_special_likes_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subset',
            name='picture',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='discount',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='special',
            name='picture',
        ),
        migrations.AddField(
            model_name='discount',
            name='picture',
            field=models.ManyToManyField(to='ghoghnoos.pictures'),
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ManyToManyField(to='ghoghnoos.pictures'),
        ),
        migrations.AddField(
            model_name='special',
            name='picture',
            field=models.ManyToManyField(to='ghoghnoos.pictures'),
        ),
    ]
