# Generated by Django 5.2.5 on 2025-08-27 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0025_pictures_category_picture_subset_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='special',
            name='picture',
        ),
        migrations.AddField(
            model_name='pictures',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ghoghnoos.discount'),
        ),
        migrations.AddField(
            model_name='pictures',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ghoghnoos.product'),
        ),
        migrations.AddField(
            model_name='pictures',
            name='special',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ghoghnoos.special'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
