# Generated by Django 5.2.5 on 2025-08-30 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0026_remove_discount_picture_remove_product_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_image', to='ghoghnoos.discount'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='ghoghnoos.product'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='special',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_image', to='ghoghnoos.special'),
        ),
        migrations.DeleteModel(
            name='Replay',
        ),
    ]
