# Generated by Django 5.2.5 on 2025-08-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghoghnoos', '0027_alter_pictures_discount_alter_pictures_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
